import { NgModule, NO_ERRORS_SCHEMA } from '@angular/core';
import { NativeScriptModule } from 'nativescript-angular/nativescript.module';

import { AppRoutingModule } from '@src/app/app-routing.module.tns';
import { AppComponent } from '@src/app/app.component';
import { AutoGeneratedComponent } from '@src/app/auto-generated/auto-generated.component';
import { HeadComponent } from '@src/app/head/head.component';
import { LeftPanelComponent } from '@src/app/left-panel/left-panel.component';
import { FooterComponent } from '@src/app/footer/footer.component';
import { LoginComponent } from '@src/app/login/login.component';
import { ThoughtCardComponent } from '@src/app/thought-card/thought-card.component';
import { ToughtHoleWallComponent } from '@src/app/tought-hole-wall/tought-hole-wall.component';
import { ThoughtHoleWallComponent } from '@src/app/thought-hole-wall/thought-hole-wall.component';


// Uncomment and add to NgModule imports if you need to use two-way binding
// import { NativeScriptFormsModule } from 'nativescript-angular/forms';

// Uncomment and add to NgModule imports  if you need to use the HTTP wrapper
// import { NativeScriptHttpClientModule } from 'nativescript-angular/http-client';

@NgModule({
  declarations: [
    AppComponent,
    AutoGeneratedComponent,
    HeadComponent,
    LeftPanelComponent,
    FooterComponent,
    LoginComponent,
    ThoughtCardComponent,
    ToughtHoleWallComponent,
    ThoughtHoleWallComponent,
  ],
  imports: [
    NativeScriptModule,
    AppRoutingModule,
  ],
  providers: [],
  bootstrap: [AppComponent],
  schemas: [NO_ERRORS_SCHEMA]
})
/*
Pass your application module to the bootstrapModule function located in main.ts to start your app
*/
export class AppModule { }
